const employee = [
  {
    id: crypto.randomUUID(),
    img: "https://randomuser.me/api/portraits/women/90.jpg",
    name: "Menna Khaled Ahmed",
    position: "HR Head",
    department: "Business Devlopment",
    attendance: "Present",
    date: "12/12/2018",
    phone: "01234567891",
    email: "sara khaled@gmail.com",
    office: "Arabic Localizer",
    role: "Employee",
    manager: "Mohamed Tarek",
  },
  {
    id: crypto.randomUUID(),
    img: "https://randomuser.me/api/portraits/women/80.jpg",
    name: "Sara Khaled Ahmed",
    position: "HR Head",
    department: "Business Devlopment",
    attendance: "Present",
    date: "12/12/2018",
    phone: "01234567891",
    email: "sara khaled@gmail.com",
    office: "Arabic Localizer",
    role: "Employee",
    manager: "Mohamed Tarek",
  },
  {
    id: crypto.randomUUID(),
    img: "https://randomuser.me/api/portraits/women/70.jpg",
    name: "Sara Khaled Ahmed",
    position: "HR Head",
    department: "Business Devlopment",
    attendance: "Absent",
    date: "12/12/2018",
    phone: "01234567891",
    email: "sara khaled@gmail.com",
    office: "Arabic Localizer",
    role: "Employee",
    manager: "Mohamed Tarek",
  },
  {
    id: crypto.randomUUID(),
    img: "https://randomuser.me/api/portraits/women/60.jpg",
    name: "Sara Khaled Ahmed",
    position: "HR Head",
    department: "Business Devlopment",
    attendance: "OnLeave",
    date: "12/12/2018",
    phone: "01234567891",
    email: "sara khaled@gmail.com",
    office: "Arabic Localizer",
    role: "Employee",
    manager: "Mohamed Tarek",
  },
  {
    id: crypto.randomUUID(),
    img: "https://randomuser.me/api/portraits/women/50.jpg",
    name: "Sara Khaled Ahmed",
    position: "HR Head",
    department: "Business Devlopment",
    attendance: "Holiday",
    date: "12/12/2018",
    phone: "01234567891",
    email: "sara khaled@gmail.com",
    office: "Arabic Localizer",
    role: "Employee",
    manager: "Mohamed Tarek",
  },
  {
    id: crypto.randomUUID(),
    img: "https://randomuser.me/api/portraits/women/40.jpg",
    name: "Sara Khaled Ahmed",
    position: "HR Head",
    department: "Business Devlopment",
    attendance: "Weekend",
    date: "12/12/2018",
    phone: "01234567891",
    email: "sara khaled@gmail.com",
    office: "Arabic Localizer",
    role: "Employee",
    manager: "Mohamed Tarek",
  },
  {
    id: crypto.randomUUID(),
    img: "https://randomuser.me/api/portraits/women/8.jpg",
    name: "Sara Khaled Ahmed",
    position: "HR Head",
    department: "Business Devlopment",
    attendance: "Absent",
    date: "12/12/2018",
    phone: "01234567891",
    email: "sara khaled@gmail.com",
    office: "Arabic Localizer",
    role: "Employee",
    manager: "Mohamed Tarek",
  },
  {
    id: crypto.randomUUID(),
    img: "https://randomuser.me/api/portraits/women/5.jpg",
    name: "Sara Khaled Ahmed",
    position: "HR Head",
    department: "Business Devlopment",
    attendance: "Absent",
    date: "12/12/2018",
    phone: "01234567891",
    email: "sara khaled@gmail.com",
    office: "Arabic Localizer",
    role: "Employee",
    manager: "Mohamed Tarek",
  },
  {
    id: crypto.randomUUID(),
    img: "https://randomuser.me/api/portraits/women/18.jpg",
    name: "Sara Khaled Ahmed",
    position: "HR Head",
    department: "Business Devlopment",
    attendance: "Absent",
    date: "12/12/2018",
    phone: "01234567891",
    email: "sara khaled@gmail.com",
    office: "Arabic Localizer",
    role: "Employee",
    manager: "Mohamed Tarek",
  },
];

export default employee;
